generatorName: typescript-axios
inputSpec: /local/openapi.json
outputDir: /local/src/api/generated
additionalProperties:
  supportsES6: true
  npmVersion: "6.9.0"
  typescriptThreePlus: true
  withSeparateModelsAndApi: true
  modelPackage: models
  apiPackage: apis
  withInterfaces: true
