version: '3.8'

services:
  test-db:
    image: postgres:16
    container_name: got-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: got_test
    ports:
      - "5433:5432"  # Using 5433 to avoid conflicts with local Postgres if installed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
